# Generated by Django 3.1.6 on 2021-02-18 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('song_rater', '0003_auto_20210217_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='song_rater.song'),
        ),
    ]
