# Generated by Django 3.1.6 on 2021-02-24 08:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('song_rater', '0005_auto_20210218_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
